libraryVersion: 0.24.0
groupId: org.mozilla.appservices
projects:
  rustlog-library:
    path: components/rc_log/android
    artifactId: rustlog
    publishedArtifacts: [rustlog, rustlog-forUnitTests, rustlog-withoutLib]
    description: Android hook into the log crate.
